### ISSUE TITLE
Support prefix, postfix and circumfix options on Output type.

### ISSUE THREAD

**Issue by flanksaul** [flanksource/konfig-manager#28]
The suggestion is supporting the following config for the konfig-manager:

```    
apiVersion: konfigmanager.flanksource.com/v1
kind: Konfig
metadata:
    name: "konfig-{{name}}"
    namespace: "{{namespace}}"
spec:
    hierarchy:
        - name: globalssys
          namespace: "{{namespace}}"
          kind: ConfigMap
    output:
        name: "{{name}}-runtime"
        namespace: "{{namespace}}"
        kind: ConfigMap
        type: file
        filetype: js
        key: runtime.js
        key-transforms:
              - prefix: __
              - postfix: __
              - circumfix: __
              - prefix: __
                postfix: __
```

Where

```
key-transforms:
      - prefix: __
      - postfix: __
      - circumfix: __
```

for single env key 'FOO', output keys are as follows:

```
window['__FOO']=<value>
window['FOO__']=<value>
window['__FOO__']=<value>
```

and where

```
key-transforms:
      - circumfix: __
```

output keys are as follows:

```
window['__FOO__']=<value>
```

And where

```
key-transforms:
      - prefix: __
        postfix: __
```

output keys are as follows:

```
window['__FOO__']=<value>
```

and [mutatis mutandis](https://en.wikipedia.org/wiki/Mutatis_mutandis) for all supported filetypes.
